# Generated by Django 5.2.4 on 2025-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='trophy_count',
        ),
        migrations.AddField(
            model_name='player',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
