# Generated by Django 5.2.4 on 2025-07-27 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_trophy_count_player_draws_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_playing',
        ),
        migrations.AddField(
            model_name='player',
            name='last_game_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_game_player', to='game.game'),
        ),
    ]
