# Generated by Django 5.2.4 on 2025-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_is_playing_player_last_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='o_peak',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='x_peak',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
